// <auto-generated />
namespace PhotoGallery2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.1-21010")]
    public sealed partial class CommentIDChanges : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CommentIDChanges));
        
        string IMigrationMetadata.Id
        {
            get { return "201406020646384_CommentID Changes"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
